name: generate-article-list
on: [push]
jobs:
  generate-article-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.8.2"
      - run: git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
      - run: git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)" 
      - run: deno run --allow-read --allow-write --allow-run listing.deno.ts
      - run: git add .
      - run: git commit -m 'update list'
      - run: git push
